services:
  haraka:
    build:
      context: .
      dockerfile: haraka.dockerfile
    container_name: haraka
    ports:
      - "2525:25"
    depends_on:
      - mailpit
    networks:
      - localnet

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP port
    networks:
      - localnet

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - localnet

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - localnet

networks:
  localnet:
    driver: bridge

volumes:
  pgdata:
    driver: local